### ISSUE TITLE
Support for rfc3062 Password Modify

### ISSUE THREAD

**Issue by mynameisrufus** [ruby-ldap/ruby-net-ldap#163]
Would be great if password modify was supported, perhaps something like:

```ruby
ldap = Net::LDAP.new(host: 127.0.0.1, port: 636, encryption: :ssl)
ldap.modify_password(dn: 'cn=Joe,ou=People', oldPassword: 'foo', newPassword: 'bar', auth: {})
                                     
```

http://tools.ietf.org/html/rfc3062

https://github.com/openldap/openldap/blob/master/clients/tools/ldappasswd.c

https://github.com/openldap/openldap/blob/master/include/ldap.h#L377

**Comment by FreekingDean** [comment]
@mynameisrufus  It looks like a lot of work was done to support this, is it ready for a pull request, or does it need some more loving?

**Comment by mtodd** [comment]
@FreekingDean there's an open PR here: https://github.com/ruby-ldap/ruby-net-ldap/pull/178. It's stalled out waiting for me since I'm still uncertain and uncomfortable accepting the specific changes to the BER syntax values. I've also had no time to dedicate to it as of late. It's still on my radar, though, and apologize for the delay.
