### ISSUE TITLE
rubygems.org documentation link is wrong

### ISSUE THREAD

**Issue by jch** [ruby-ldap/ruby-net-ldap#218]
Follow up to https://github.com/ruby-ldap/ruby-net-ldap/issues/215. I can't figure out where this link value is set:

![2015-09-18 at 9 55 am](https://cloud.githubusercontent.com/assets/19874/9965499/79298da4-5deb-11e5-9d71-d876e24dac33.png)

It should be http://www.rubydoc.info/gems/ruby-net-ldap/Net/LDAP, but is incorrectly http://rubyldap.github.io/. I couldn't find it in the gemspec or from the rubygems.org guide. If anyone figures it out, I'd love a PR.

cc @ruby-ldap/ruby-ldap-admins @satoryu

**Comment by satoryu** [comment]
This is because you're not registered as author of the gem, I think. 
In the case of the gem I own, I can see the link to edit page:

<img width="1005" alt="cursor_and_google_suggest___rubygems_org___your_community_gem_host" src="https://cloud.githubusercontent.com/assets/124871/9972839/6aa588c8-5ea4-11e5-804c-4dd42f9571d4.png">

and the edit page allows to update the link to documentation: 

<img width="722" alt="cursor_and_edit_links___rubygems_org___your_community_gem_host" src="https://cloud.githubusercontent.com/assets/124871/9972866/0a34dfec-5ea5-11e5-8e5a-657c4e196043.png">

I guess that you need to be owner. The current owners can add you as new owner with [`gem owner` command](http://guides.rubygems.org/command-reference/#gem-owner).

**Comment by jch** [comment]
@satoryu thank you! I am an owner, I just wasn't signed in. User error, sigh :grin:
